name: Deploy and Simulate Traffic

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Output ALB DNS Name
        run: terraform output alb_dns_name > alb_dns_name.txt
        working-directory: ./terraform

      - name: Upload ALB DNS Name Artifact
        uses: actions/upload-artifact@v4
        with:
          name: alb-dns
          path: ./terraform/alb_dns_name.txt

  simulate:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Wait for infra to settle
        run: sleep 60

      - uses: actions/checkout@v3

      - name: Download ALB DNS Name
        uses: actions/download-artifact@v4
        with:
          name: alb-dns
          path: .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run traffic simulation
        run: python traffic_simulation.py