name: Simulate Traffic

on:
  workflow_dispatch:

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download ALB DNS Name
        uses: actions/download-artifact@v4
        with:
          name: alb-dns
          path: .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run traffic simulation
        run: python simulate_traffic.py